
name: Validate on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.3
    - run: bun install
    - run: bun validate
    - run: bun run build
